# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: serverdocker build
      run: docker build -t serverdocker-update .
    - name: server-junit container build and run
      run: |
        echo Starting testing,
        docker build -f DockerfileForTests -t server-junit . 
        docker run server-junit  
  checkstyle_job:
        runs-on: ubuntu-latest
        needs: [build_and_test]
        name: Checkstyle job
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run check style
          uses: nikitasavinov/checkstyle-action@master
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            reporter: 'github-pr-check'
  dockerhub:
        runs-on: ubuntu-latest
        needs: [build_and_test]
        steps:
          - uses: actions/checkout@v2
            env: 
              LOGIN: ${{ secrets.DOCKER_HUB_USERNAME }}
              PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          - name: build  
            run: docker build -t $LOGIN/servdocker:ver$GITHUB_RUN_NUMBER .
          - name: login and push
            run: |
              docker login --username=$LOGIN --password=$PASSWORD
              docker push $LOGIN/servdocker:ver_$GITHUB_RUN_NUMBER 
